{% set name = "angelcommunity" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/angelcommunity-{{ version }}.tar.gz
  sha256: 55960184fb5d2b9d16eaa9a96db8531ffcf1b355062f6f179ea670d46706a480

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation 
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - future
    - tqdm
    - python-igraph
    - networkx >=3.0
    - numpy

test:
  imports:
    - angel
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/GiulioRossetti/ANGEL
  summary: Community Discovery algorithm
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mediocretech
